


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."difficulty" AS ENUM (
    'easy',
    'medium',
    'hard'
);


ALTER TYPE "public"."difficulty" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."game_records" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "has_timed_mode_enabled" boolean,
    "difficulty" "public"."difficulty",
    "points" bigint,
    "words" bigint,
    "time_playing" bigint
);


ALTER TABLE "public"."game_records" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."game_records_with_usernames" AS
 SELECT "gr"."id",
    "gr"."user_id",
    "gr"."created_at",
    "gr"."has_timed_mode_enabled",
    "gr"."difficulty",
    "gr"."points",
    "gr"."words",
    "gr"."time_playing",
    COALESCE(("au"."raw_user_meta_data" ->> 'username'::"text"), 'Player'::"text") AS "username"
   FROM ("public"."game_records" "gr"
     LEFT JOIN "auth"."users" "au" ON (("gr"."user_id" = "au"."id")));


ALTER VIEW "public"."game_records_with_usernames" OWNER TO "postgres";


ALTER TABLE "public"."game_records" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."records_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."game_records"
    ADD CONSTRAINT "records_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_game_records_created_at" ON "public"."game_records" USING "btree" ("created_at" DESC);



CREATE INDEX "idx_game_records_difficulty_points" ON "public"."game_records" USING "btree" ("difficulty", "points" DESC);



CREATE INDEX "idx_game_records_points" ON "public"."game_records" USING "btree" ("points" DESC);



CREATE INDEX "idx_game_records_user_id" ON "public"."game_records" USING "btree" ("user_id");



ALTER TABLE ONLY "public"."game_records"
    ADD CONSTRAINT "records_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



CREATE POLICY "Anyone can view game records" ON "public"."game_records" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Users can insert their own game records" ON "public"."game_records" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."game_records" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."game_records" TO "anon";
GRANT ALL ON TABLE "public"."game_records" TO "authenticated";
GRANT ALL ON TABLE "public"."game_records" TO "service_role";



GRANT ALL ON TABLE "public"."game_records_with_usernames" TO "anon";
GRANT ALL ON TABLE "public"."game_records_with_usernames" TO "authenticated";
GRANT ALL ON TABLE "public"."game_records_with_usernames" TO "service_role";



GRANT ALL ON SEQUENCE "public"."records_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."records_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."records_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


