-- Create words table
CREATE TABLE IF NOT EXISTS public.words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word TEXT NOT NULL,
  difficulty_value INTEGER NOT NULL CHECK (difficulty_value >= 1 AND difficulty_value <= 100),
  locale TEXT NOT NULL DEFAULT 'en',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT words_word_locale_unique UNIQUE (word, locale)
);

-- Create tags table
CREATE TABLE IF NOT EXISTS public.tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag TEXT NOT NULL,
  locale TEXT NOT NULL DEFAULT 'en',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT tags_tag_locale_unique UNIQUE (tag, locale)
);

-- Create word_tags junction table for many-to-many relationship
CREATE TABLE IF NOT EXISTS public.word_tags (
  word_id BIGINT NOT NULL REFERENCES public.words(id) ON DELETE CASCADE,
  tag_id BIGINT NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
  PRIMARY KEY (word_id, tag_id)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_words_locale ON public.words(locale);
CREATE INDEX IF NOT EXISTS idx_words_difficulty ON public.words(difficulty_value);
CREATE INDEX IF NOT EXISTS idx_words_locale_difficulty ON public.words(locale, difficulty_value);
CREATE INDEX IF NOT EXISTS idx_tags_locale ON public.tags(locale);
CREATE INDEX IF NOT EXISTS idx_word_tags_word_id ON public.word_tags(word_id);
CREATE INDEX IF NOT EXISTS idx_word_tags_tag_id ON public.word_tags(tag_id);

-- Enable Row Level Security
ALTER TABLE public.words ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.word_tags ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Everyone can read words, tags, and word_tags (authenticated users)
CREATE POLICY "Anyone authneticated can view words"
ON public.words FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Anyone authneticated can view tags"
ON public.tags FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Anyone authneticated can view word_tags"
ON public.word_tags FOR SELECT
TO authenticated
USING (true);

-- Only service role can insert/update/delete (for admin operations)
-- These policies are intentionally not created to restrict modifications
-- Use service role or admin panel for data management

-- Create a view to fetch words with their tags
CREATE OR REPLACE VIEW public.words_with_tags AS
SELECT 
    w.id,
    w.word,
    w.difficulty_value,
    w.locale,
    w.created_at,
    ARRAY_AGG(t.tag ORDER BY t.tag) FILTER (WHERE t.tag IS NOT NULL) as tags
FROM public.words w
LEFT JOIN public.word_tags wt ON w.id = wt.word_id
LEFT JOIN public.tags t ON wt.tag_id = t.id
GROUP BY w.id, w.word, w.difficulty_value, w.locale, w.created_at;

-- Grant SELECT permission on the view
GRANT SELECT ON public.words_with_tags TO authenticated;

COMMENT ON TABLE public.words IS 'Stores words for the Hangman game with difficulty values and locale';
COMMENT ON TABLE public.tags IS 'Stores descriptive tags/hints for words';
COMMENT ON TABLE public.word_tags IS 'Junction table linking words to their tags';
COMMENT ON VIEW public.words_with_tags IS 'View that returns words with their associated tags as an array';

